name: flutter_dial
description: A skeuomorphic dial widget that outputs rotation degrees, percent rotation, and current dial stop.
version: 0.1.6
homepage: https:/www.eleniak.ca
repository: https://github.com/beleniak/flutter_dial.git

environment:
  sdk: ">=3.2.0 <4.0.0"
#  flutter: "3.35.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
